-- ==========================================
-- RISEN Knowledge OS
-- Migration
-- 002-add-user-service-periods.sql
-- ==========================================

CREATE TABLE IF NOT EXISTS user_service_periods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  user_id BIGINT NOT NULL REFERENCES users(id),

  service_type TEXT NOT NULL DEFAULT 'regular',
  status TEXT NOT NULL DEFAULT 'active',

  start_date DATE NOT NULL,
  end_date DATE,

  memo TEXT,

  active BOOLEAN NOT NULL DEFAULT TRUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
